# Generated by Django 5.2 on 2025-04-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_uva_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('acceptance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('difficulty', models.CharField(max_length=50)),
                ('solved', models.PositiveIntegerField()),
                ('url', models.URLField()),
            ],
        ),
    ]
